<a href="https://colab.research.google.com/github/GJaySri/My-project/blob/main/finalproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

# install
!pip install Pyspark

# start spark session
from pyspark.sql import SparkSession

spark=SparkSession.builder.getOrCreate()
spark




     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 MB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for Pyspark: filename=pyspark-3.4.1-py2.py3-none-any.whl size=311285388 sha256=f1df50bcd0da94baeabfc185cf890d6e6241c67f05c9de55498fcfecd77dab86
  Stored in directory: /root/.cache/pip/wheels/0d/77/a3/ff2f74cc9ab41f8f594dabf0579c2a7c6de920d584206e0834
Successfully built Pyspark


In [3]:

# read sklearn inbuilt data
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
wine = load_wine(as_frame=True)
wine = wine.frame
wine = spark.createDataFrame(wine)


In [4]:
wine.show()


+-------+----------+----+-----------------+---------+-------------+----------+--------------------+---------------+---------------+----+----------------------------+-------+------+
|alcohol|malic_acid| ash|alcalinity_of_ash|magnesium|total_phenols|flavanoids|nonflavanoid_phenols|proanthocyanins|color_intensity| hue|od280/od315_of_diluted_wines|proline|target|
+-------+----------+----+-----------------+---------+-------------+----------+--------------------+---------------+---------------+----+----------------------------+-------+------+
|  14.23|      1.71|2.43|             15.6|    127.0|          2.8|      3.06|                0.28|           2.29|           5.64|1.04|                        3.92| 1065.0|     0|
|   13.2|      1.78|2.14|             11.2|    100.0|         2.65|      2.76|                0.26|           1.28|           4.38|1.05|                         3.4| 1050.0|     0|
|  13.16|      2.36|2.67|             18.6|    101.0|          2.8|      3.24|                 

wine.printSchema()


In [6]:
wine.columns


['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline',
 'target']

In [9]:
from pyspark.ml.feature import VectorAssembler
featureassembler= VectorAssembler(inputCols=['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline'], outputCol='Features')


output = featureassembler.transform(wine)



In [10]:

output.show()


+-------+----------+----+-----------------+---------+-------------+----------+--------------------+---------------+---------------+----+----------------------------+-------+------+--------------------+
|alcohol|malic_acid| ash|alcalinity_of_ash|magnesium|total_phenols|flavanoids|nonflavanoid_phenols|proanthocyanins|color_intensity| hue|od280/od315_of_diluted_wines|proline|target|            Features|
+-------+----------+----+-----------------+---------+-------------+----------+--------------------+---------------+---------------+----+----------------------------+-------+------+--------------------+
|  14.23|      1.71|2.43|             15.6|    127.0|          2.8|      3.06|                0.28|           2.29|           5.64|1.04|                        3.92| 1065.0|     0|[14.23,1.71,2.43,...|
|   13.2|      1.78|2.14|             11.2|    100.0|         2.65|      2.76|                0.26|           1.28|           4.38|1.05|                         3.4| 1050.0|     0|[13.2,1.78,2

In [11]:

modeldata=output.select('Features','target')

In [12]:

modeldata.show()

+--------------------+------+
|            Features|target|
+--------------------+------+
|[14.23,1.71,2.43,...|     0|
|[13.2,1.78,2.14,1...|     0|
|[13.16,2.36,2.67,...|     0|
|[14.37,1.95,2.5,1...|     0|
|[13.24,2.59,2.87,...|     0|
|[14.2,1.76,2.45,1...|     0|
|[14.39,1.87,2.45,...|     0|
|[14.06,2.15,2.61,...|     0|
|[14.83,1.64,2.17,...|     0|
|[13.86,1.35,2.27,...|     0|
|[14.1,2.16,2.3,18...|     0|
|[14.12,1.48,2.32,...|     0|
|[13.75,1.73,2.41,...|     0|
|[14.75,1.73,2.39,...|     0|
|[14.38,1.87,2.38,...|     0|
|[13.63,1.81,2.7,1...|     0|
|[14.3,1.92,2.72,2...|     0|
|[13.83,1.57,2.62,...|     0|
|[14.19,1.59,2.48,...|     0|
|[13.64,3.1,2.56,1...|     0|
+--------------------+------+
only showing top 20 rows



In [13]:
train_data,test_data=modeldata.randomSplit([0.8,0.2])


In [14]:
train_data.show()


+--------------------+------+
|            Features|target|
+--------------------+------+
|[11.64,2.06,2.46,...|     1|
|[11.65,1.67,2.62,...|     1|
|[11.66,1.88,1.92,...|     1|
|[11.84,2.89,2.23,...|     1|
|[12.0,0.92,2.0,19...|     1|
|[12.08,1.13,2.51,...|     1|
|[12.16,1.61,2.31,...|     1|
|[12.17,1.45,2.53,...|     1|
|[12.21,1.19,1.75,...|     1|
|[12.29,1.61,2.21,...|     1|
|[12.33,1.1,2.28,1...|     1|
|[12.37,0.94,1.36,...|     1|
|[12.37,1.17,1.92,...|     1|
|[12.37,1.21,2.56,...|     1|
|[12.64,1.36,2.02,...|     1|
|[12.7,3.87,2.4,23...|     1|
|[12.72,1.81,2.2,1...|     1|
|[12.85,1.6,2.52,1...|     0|
|[12.99,1.67,2.6,3...|     1|
|[13.03,0.9,1.71,1...|     1|
+--------------------+------+
only showing top 20 rows



In [15]:
from pyspark.ml.classification import RandomForestClassifier


rf = RandomForestClassifier(featuresCol='Features', labelCol='target')


rf = rf.fit(train_data)


# prediction
y_pred = rf.transform(test_data)


y_pred.show()


+--------------------+------+--------------------+--------------------+----------+
|            Features|target|       rawPrediction|         probability|prediction|
+--------------------+------+--------------------+--------------------+----------+
|[11.84,0.89,2.58,...|     1|  [0.125,18.875,1.0]|[0.00625,0.94375,...|       1.0|
|[11.96,1.09,2.3,2...|     1|   [9.125,9.875,1.0]|[0.45625,0.49375,...|       1.0|
|[12.33,0.99,1.95,...|     1|      [5.0,15.0,0.0]|     [0.25,0.75,0.0]|       1.0|
|[12.37,1.13,2.16,...|     1|  [0.125,19.875,0.0]|[0.00625,0.99375,...|       1.0|
|[12.67,0.98,2.24,...|     1|      [0.0,20.0,0.0]|       [0.0,1.0,0.0]|       1.0|
|[12.93,3.8,2.65,1...|     0|[8.10119047619047...|[0.40505952380952...|       1.0|
|[13.24,2.59,2.87,...|     0|[16.4761904761904...|[0.82380952380952...|       0.0|
|[13.29,1.97,2.68,...|     0|[19.9761904761904...|[0.99880952380952...|       0.0|
|[13.34,0.94,2.36,...|     1|      [4.0,14.0,2.0]|       [0.2,0.7,0.1]|       1.0|
|[13

In [16]:
# confusion matrix
y_pred.groupBy('target', 'prediction').count().show()

+------+----------+-----+
|target|prediction|count|
+------+----------+-----+
|     0|       1.0|    1|
|     0|       0.0|    9|
|     1|       1.0|   13|
|     2|       2.0|    7|
+------+----------+-----+



In [17]:

from sklearn.metrics import confusion_matrix
pred=y_pred.select("prediction").collect()
orig=y_pred.select("target").collect()
print(confusion_matrix(orig, pred))

[[ 9  1  0]
 [ 0 13  0]
 [ 0  0  7]]


In [18]:
from pyspark.ml.evaluation import MulticlassClassificationEvaluator


evaluator = MulticlassClassificationEvaluator(
    labelCol='target', predictionCol='prediction')


accuracy = evaluator.evaluate(y_pred)
accuracy


0.9664067576348279

In [19]:
spark.stop()